version: '3.8'

services:
  pocketbase:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/app/pb_data
      - ./backend/pb_migrations:/app/pb_migrations
    environment:
      - PB_DATA_DIR=/app/pb_data
      - PB_MIGRATIONS_DIR=/app/pb_migrations
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  dashboard:
    build:
      context: ./web-dashboard
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - VITE_POCKETBASE_URL=http://pocketbase:8090
      - NODE_ENV=production
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Reverse proxy (opcjonalnie)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - dashboard
      - pocketbase
    restart: unless-stopped
    profiles:
      - production

volumes:
  pb_data:
    driver: local

networks:
  default:
    name: allegro-monitor 